# Dataset Configuration
data_path: "data/raw/facebook-hateful-memes"
labels_relative_location: "fine_grained_labels/dev_unseen.jsonl"
prompts_file: "data/processed/img_classification_prompts.pqt"
max_samples: null  # Set to a number to limit samples, or null for all
output_path: "data/results/img_classification/[MODEL_NAME]/[DATETIME].json"

# Model Configuration
models:
  - "HuggingFaceM4/Idefics3-8B-Llama3"
  - "Qwen/Qwen2.5-VL-7B-Instruct"
  - "Qwen/Qwen2.5-VL-32B-Instruct"

model_id: 0
resolution_factor: 4
max_new_tokens: 50

# Pipeline Configuration
batch_size: 2
num_workers: 10