# Dataset Configuration
data_path: "data/raw/yoder_data/sampled/identity_hate_corpora.jsonl"
prompts_file: "data/processed/classification_prompts/[DATASET]_[MODEL_NAME]_corners.pqt"
max_samples: null  # Set to a number to limit samples, or null for all
output_path: "data/results/text_classification/[MODEL_NAME]/[DATETIME].json"

# Model Configuration
model_id: "meta-llama/Llama-3.1-8B-Instruct"
vllm_seed: 22
temperature: 0.0  # 0.0 for deterministic, higher for more randomness
top_p: 1.0
max_model_len: 400
max_num_seqs: 120

# Pipeline Configuration
batch_size: 16
num_workers: 4
dataset_seed: 42